package com.sample
 
import com.sample.DroolsTest.Message;
 
rule "rule1"
    when
        m : Message(  )
    then
        System.out.println( kcontext.getRule().getName() + ", " + m);
end

rule "rule2"
    when
        m : Message(  )
    then
        System.out.println( kcontext.getRule().getName() + ", " + m);
end

rule "rule3"
    when
        m : Message(  )
    then
        System.out.println( kcontext.getRule().getName() + ", " + m);
end

