package example.scorecard_example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private double score;
   private Double age;
   private java.lang.String name;

   public Customer()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public double getScore()
   {
      return this.score;
   }

   public void setScore(double score)
   {
      this.score = score;
   }

   public java.lang.Double getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Double age)
   {
      this.age = age;
   }

   public Customer(double score, java.lang.Double age, java.lang.String name)
   {
      this.score = score;
      this.age = age;
      this.name = name;
   }

}