package com.sample
 
import com.sample.DroolsTest.Message;
 
rule "Hello1"
	lock-on-active
    when
        m : Message( status == Message.HELLO )
    then
        System.out.println( "message = " + m.getMessage());
        m.setMessage(  kcontext.getRule().getName() + " is fired" );
        update( m );
end

rule "Hello2"
	lock-on-active
    when
        m : Message( status == Message.HELLO )
    then
        System.out.println( "message = " + m.getMessage());
        m.setMessage(  kcontext.getRule().getName() + " is fired" );
        update( m );
end

rule "Hello3"
	lock-on-active
    when
        m : Message( status == Message.HELLO )
    then
        System.out.println( "message = " + m.getMessage());
        m.setMessage(  kcontext.getRule().getName() + " is fired" );
        update( m );
end