package com.sample
 
import com.sample.Person;
 
rule "Older than 30, earn more than 1900"
    when
        forall($p : Person( age > 30)
                    Person( this == $p, salary >  1900 )
        )
    then
        System.out.println( "Older than 30, earn more than 1900" );
end

rule "test1"
    when
        forall($p : Person( age > 23)
                    Person( this == $p, salary >  1900 )
        )
    then
        System.out.println( "test1" );
end

rule "test2"
    when
        not($p : Person( age > 500) and not ( Person( this == $p, salary >  1900 ) ) )
    then
        System.out.println( "test2" );
end

rule "test3"
    when
        forall( Person( age > 22) )
    then
        System.out.println( "test3" );
end