package com.sample
 
import com.sample.Person;
import java.util.List;

global java.util.List results;

rule "Insert from List"
	ruleflow-group "group0"
	when
		$list : List()
		$p : Person() from $list
	then
		System.out.println("going to insert " + $p);
		insert($p);
		((org.drools.core.common.InternalAgenda)kcontext.getKnowledgeRuntime().getAgenda()).activateRuleFlowGroup("group1");
end

rule "Hello Group1"
	ruleflow-group "group1"
    when
        $p : Person()
    then
        System.out.println( "Hello Group1 is called for : " + $p );
        $p.setSalary($p.getSalary() + 100);
        ((org.drools.core.common.InternalAgenda)kcontext.getKnowledgeRuntime().getAgenda()).activateRuleFlowGroup("group2");
end

rule "Hello Group2"
	ruleflow-group "group2"
    when
        $p : Person()
    then
        System.out.println( "Hello Group2 is called for : " + $p );
        $p.setSalary($p.getSalary() + 200);
        ((org.drools.core.common.InternalAgenda)kcontext.getKnowledgeRuntime().getAgenda()).activateRuleFlowGroup("group3");
end

rule "Remove from List"
	ruleflow-group "group3"
    when
        $list : List()
        $p : Person()
    then
        retract($p);
        $list.remove($p);
        results.add($p);
        update($list);
end
