package com.sample
 
import com.sample.Person;
import java.util.List;

global java.util.List results;

rule "Insert from List"
	ruleflow-group "group0"
	when
		$list : List()
	then
		Person person = (Person)$list.get(0);
		System.out.println("going to insert " + person);
		insert(person);
end

rule "Hello Group1"
	ruleflow-group "group1"
    when
        $p : Person()
    then
        System.out.println( "Hello Group1 is called for : " + $p );
        $p.setSalary($p.getSalary() + 100);
end

rule "Hello Group2"
	ruleflow-group "group2"
    when
        $p : Person()
    then
        System.out.println( "Hello Group2 is called for : " + $p );
        $p.setSalary($p.getSalary() + 200);
end

rule "Remove from List"
	ruleflow-group "group3"
    when
        $list : List()
        $p : Person()
    then
        retract($p);
        $list.remove($p);
        results.add($p);
        update($list);
end
